### ISSUE TITLE
unhashable type: 'set' error

### ISSUE THREAD

**Issue by RuslanMamedov** [Featuretools/featuretools#624]
### Hi there! I'm trying to implement FT for my kaggle kernel but it's giving me the error "unhashable type: 'set' . I couldn't find any set in the dataframe I use. Do you mind taking a look? Thanks. https://www.kaggle.com/ruslanmamedov/poverty-level-prediction-beginer-s-kernel/edit

-----
*Issues created here on Github are for bugs or feature requests. For usage questions and questions about errors, please ask on Stack Overflow with the [featuretools](https://stackoverflow.com/questions/tagged/featuretools) tag. Check the [documentation](https://docs.featuretools.com/#get-help) for further guidance on where to ask your question.*

#### Bug/Feature Request Description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

#### Output of ``featuretools.show_info()``

<details>

[paste the output of ``featuretools.show_info()`` here below this line]

</details>

**Comment by kmax12** [comment]
This was fixed in #615, which will be released in the next version of Featuretools. In the meantime, can you try to install Featuretools directly from master?

That can be done with the following command

```pip install https://github.com/featuretools/featuretools/zipball/master```

The other option is to update to pandas 0.24.2.

Please let us know if that helps.

**Comment by RuslanMamedov** [comment]
installed FT package but still getting the same error: https://www.kaggle.com/ruslanmamedov/poverty-level-prediction-beginer-s-kernel

**Comment by kmax12** [comment]
since it is already installed, you actually need to run that with the upgrade command. Try 

```pip install --upgrade https://github.com/featuretools/featuretools/zipball/master```

**Comment by RuslanMamedov** [comment]
That worked, thanks!

**Comment by kmax12** [comment]
This is fixed and has been released in Featuretools 0.9.1. If you upgrade to the latest version of Featuretools, it will go away.
